[package]
name = "docker_http_proxy"
version = "0.1.0"
edition = "2021"

[dependencies]
# Runtime async
tokio = { version = "1", features = ["full"] }

# Serveur HTTP
hyper = { version = "0.14", features = ["full"] }

# Client HTTP permettant de contacter Docker Hub
reqwest = { version = "0.11", features = ["json", "gzip", "brotli", "deflate", "rustls-tls"] }

# JSON
serde = { version = "1", features = ["derive"] }

# Gestion d'erreurs simple
anyhow = "1"

# Accès fichiers avancé
tokio-util = "0.7"
